first pytest case implemented
EcohydrologyTeam/ClearWater-riverine pull request #32
Opened 2023-08-31 19:06 UTC by jrutyna

The first pytest case has been implemented on the two by one mesh. This test for plan02 checks the ending mass in the domain against the known mass which is calculated from the final cell volumes and the known concentration of both cell being at 100 mg/L.

2023-08-31 19:08 UTC, jrutyna commented
@sjordan29 and @xaviernogueira, can you please review my branch to see if you agree with how I structured the pytest case before I continue creating more tests?

2023-08-31 19:16 UTC, xaviernogueira commented on tests/test_final_mass.py
Some pytest feedback:
* I'd test `_mass_bal_global()` and '_mass_bal_global_100_ans' separately (i.e., different `test_...` functions). 
* The functions could take plan02 which could be a fixture.

2023-08-31 19:23 UTC, xaviernogueira commented on examples/data/simple_test_cases/plan03_2x1/cwr_initial_conditions_p03.csv
**This applied to all the `simple_test_cases/`:** but if it's only used for the tests, it would be better placed in `tests/data/plane03...`. The idea is that one shouldn't have to expect that those files (and their exact locations) are required for the tests to pass, if someone edited the CSV it could unknowingly/silently make it look like the calculations are failing. Or someone could rename/move a part of the path. 

Additionally, keeping `tests/` as a self-isolated module is best practice.

That said if you also intend to use in the sample case in an example notebook, then it may be okay to leave it where it is. However, even in that case I'd recommend importing from the tests directory, rather than the other way around for the reasons mentioned above.

2023-08-31 19:23 UTC, jrutyna commented on tests/test_final_mass.py
`_mass_bal_global_100_ans()` is needed to calculate the correct answer for '_mass_bal_global'. Would you be willing to demonstrate how to use plan02 as a fixture?

2023-08-31 19:23 UTC, xaviernogueira requested changes
Left two comments

2023-08-31 19:24 UTC, xaviernogueira commented on tests/test_final_mass.py
Yes, I can call?

2023-08-31 19:26 UTC, jrutyna commented on examples/data/simple_test_cases/plan03_2x1/cwr_initial_conditions_p03.csv
The note @sjordan29 had in tests readme file indicated where I should place the datasets. @sjordan29, do you have an opinion on where these files should go?

2023-08-31 19:58 UTC, xaviernogueira commented on tests/test_final_mass.py
Update from call:
* Root path to data for could be a fixture.
* Each path## can be a fixture that has the root path fixture as an argument.
* Then have a simple test for each path## that takes it as an argument.

Not the best place for these practices to shine as it's a better fit for testing functions, not testing one function with different inputs. That said, should be easy changes and good practice.

2023-08-31 20:59 UTC, sjordan29 commented on examples/data/simple_test_cases/plan03_2x1/cwr_initial_conditions_p03.csv
I'd agree to just place the datasets in a `tests/data` folder. It looks like Anthony added that text in the tests readme as we were restructuring the repo last year, but we've learned a lot more about testing since then. I don't anticipate that this mini model would be used for anything besides testing, so I think it makes the most sense to live within the testing repo.

2023-09-01 19:03 UTC, xaviernogueira commented on tests/test_final_mass.py
This has been implemented with this commit [https://github.com/EcohydrologyTeam/ClearWater-riverine/pull/32/commits/164b74da91ebff2681a99f7c89a151901166deaa]

2023-09-01 19:04 UTC, xaviernogueira commented on examples/data/simple_test_cases/plan03_2x1/cwr_initial_conditions_p03.csv
This has been implemented with this [commit](https://github.com/EcohydrologyTeam/ClearWater-riverine/pull/32/commits/164b74da91ebff2681a99f7c89a151901166deaa)

2023-09-01 19:05 UTC, xaviernogueira approved these changes
Changes approved! Thanks Jason

2023-09-01 19:14 UTC, aufdenkampe commented on examples/data/simple_test_cases/plan03_2x1/cwr_initial_conditions_p03.csv
@jrutyna, I agree with @xaviernogueira's suggestion, and @sjordan29 had it right that we've learned a ton since then. We'll want to change that readme.

2023-09-01 19:14 UTC, aufdenkampe commented
Thanks @jrutyna for moving this forward and to @xaviernogueira and @sjordan29 for your rapid review and responses!

2023-09-01 20:25 UTC, jrutyna commented on examples/data/simple_test_cases/plan03_2x1/cwr_initial_conditions_p03.csv
`tests/readme.md` has been updated with this [commit](https://github.com/EcohydrologyTeam/ClearWater-riverine/pull/32/commits/7f8a09af60fafd6e34e5de66e4aa060b3dcc534d)

2023-09-01 20:26 UTC, merged